name: lukhu_packages_pkg
description: A package to manage all the lukhu packages and plugins install
version: 0.0.2
homepage: /*
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  badges: 3.0.2
  flutter:
    sdk: flutter
  flutter_svg: 2.0.0+1  
  fluttertoast: ^8.1.2
  http: ^0.13.5
  nested: ^1.0.0
  provider: ^6.0.5
  shimmer: ^2.0.0
  url_launcher: ^6.1.7
  firebase_core: ^2.4.1
  device_info_plus: ^8.1.0


  #lukhu custom packages

  auth_plugin:
    git: 
     url: https://github.com/Ow3nso/auth_plugin.git
     ref: main
  
  navigation_controller_pkg:
    git: 
      url: https://github.com/Ow3nso/navigation_controller_pkg.git
      ref: main
  product_listing_pkg:
    git: 
      url: https://github.com/Ow3nso/product_listing_pkg.git
      ref: main
  chat_pkg:
    git: 
      url: https://github.com/Ow3nso/chat_pkg.git
      ref: main
  sales_pkg:
    git: 
      url: https://github.com/Ow3nso/sales_pkg.git
      ref: main
  lukhu_pay:
    git: 
      url: https://github.com/Ow3nso/lukhu_pay.git
      ref: main

  dukastax_pkg:
    git: 
      url: https://github.com/Ow3nso/dukastax_pkg.git
      ref: main

  image_picker: ^0.8.6
  dotted_border: ^2.0.0+3
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.3
  firebase_auth: ^4.2.8
  cloud_firestore: ^4.4.2
  firebase_messaging: ^14.2.4
  firebase_storage: ^11.0.13
  firebase_crashlytics: ^3.0.14
  firebase_dynamic_links: ^5.0.17
  firebase_remote_config: ^3.0.12
  pin_code_fields: ^7.4.0
  flutter_facebook_auth: ^5.0.7
  intl: ^0.17.0
  uuid: ^3.0.7
  google_sign_in: ^5.4.4
  package_info_plus: ^3.0.3
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  avatar_glow: ^2.0.2
  file_picker: ^5.2.5
  mime: ^1.0.4
  path: ^1.8.2
  path_provider: ^2.0.13
  dynamic_color: ^1.6.2
  share_plus: ^6.3.1
  cached_network_image: ^3.2.3
  qr_flutter: ^4.0.0
  glassmorphism: ^3.0.0
  fl_chart: ^0.61.0
  image: ^4.0.15
  painter: ^2.0.0
  permission_handler: ^10.2.0
  skeleton_loader: ^2.0.0+4
  go_router: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
